version: '3.6'

services:

  ia_cpp_subscriber:
    depends_on:
      - ia_eiibase
      - ia_common
    build:
      context: $PWD/../CppSubscriber
      dockerfile: $PWD/../CppSubscriber/Dockerfile
      args:
        EII_VERSION: ${EII_VERSION}
        EII_UID: ${EII_UID}
        EII_USER_NAME: ${EII_USER_NAME}
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
        UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
        CMAKE_INSTALL_PREFIX: ${EII_INSTALL_PATH}
        # set CMAKE_BUILD_TYPE value to "Debug" to generate debug symbols
        CMAKE_BUILD_TYPE: "Release"
    image: ${DOCKER_REGISTRY}ia_cpp_subscriber:${EII_VERSION}
    container_name: ia_cpp_subscriber 
    hostname: ia_cpp_subscriber
    restart: unless-stopped
    read_only: true
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m
    environment:
      AppName: "CppSubscriber"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      ETCD_PREFIX: ${ETCD_PREFIX}
      CertType: "zmq"
    networks:
      - eii
    volumes:
      - "vol_eii_socket:${SOCKET_DIR}"
    secrets:
      - ca_etcd
      - etcd_CppSubscriber_cert
      - etcd_CppSubscriber_key

secrets:
  etcd_CppSubscriber_cert:
    file: provision/Certificates/CppSubscriber/CppSubscriber_client_certificate.pem
  etcd_CppSubscriber_key:
    file: provision/Certificates/CppSubscriber/CppSubscriber_client_key.pem
