version: '3.6'

services:

  ia_python_publisher:
    depends_on:
      - ia_eisbase
    build:
      context: $PWD/../PythonPublisher
      dockerfile: $PWD/../PythonPublisher/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        EIS_USER_NAME: ${EIS_USER_NAME}
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
        # set CMAKE_BUILD_TYPE value to "Debug" to generate debug symbols
        CMAKE_BUILD_TYPE: "Release"
    image: ${DOCKER_REGISTRY}ia_python_publisher:${EIS_VERSION}
    container_name: ia_python_publisher
    hostname: ia_python_publisher
    network_mode: host
    restart: unless-stopped
    user: ${EIS_UID}
    read_only: true
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m
    environment:
      AppName: "PythonPublisher"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${eis_no_proxy},${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      ETCD_PREFIX: ${ETCD_PREFIX}
      CertType: "zmq"
      # ZMQ_RECV_HWM: "1000"
    volumes:
      - "vol_eis_socket:${SOCKET_DIR}"
    secrets:
      - ca_etcd
      - etcd_PythonPublisher_cert
      - etcd_PythonPublisher_key

secrets:
  etcd_PythonPublisher_cert:
    file: provision/Certificates/PythonPublisher/PythonPublisher_client_certificate.pem
  etcd_PythonPublisher_key:
    file: provision/Certificates/PythonPublisher/PythonPublisher_client_key.pem
