# ImageStore dockerfile
ARG EIS_VERSION
FROM ia_eisbase:$EIS_VERSION as eisbase

WORKDIR ${GO_WORK_DIR}

FROM ia_common:$EIS_VERSION as common

FROM eisbase

COPY --from=common ${GO_WORK_DIR}/common/libs ${GO_WORK_DIR}/common/libs
COPY --from=common ${GO_WORK_DIR}/common/util ${GO_WORK_DIR}/common/util
COPY --from=common /usr/local/lib /usr/local/lib
COPY --from=common /usr/local/include /usr/local/include
COPY --from=common ${GO_WORK_DIR}/../EISMessageBus ${GO_WORK_DIR}/../EISMessageBus

COPY ./publisher ./publisher

RUN go build -o ${GO_WORK_DIR}/publisher/main publisher/*.go

ENTRYPOINT ["/EIS/go/src/IEdgeInsights/publisher/main"]